### ISSUE TITLE
How to use in Django2.0

### ISSUE THREAD

**Issue by hexinatgithub** [kstateome/django-cas#74]
In main urls.py, I write
```
    url(r'^accounts/login/$', 'cas.views.login', name='login'),
    url(r'^accounts/logout/$', 'cas.views.logout', name='logout'),
```
I add everything mention in the README.md in settings.py

When I run command to start the server, error Throw
```
  File "/home/hexin/Work/项目管理/06-程序代码/website/website/urls.py", line 22, in <module>
    url(r'^accounts/login/$', 'cas.views.login', name='login'),
  File "/usr/local/lib/python3.5/dist-packages/django/conf/urls/__init__.py", line 13, in url
    return re_path(regex, view, kwargs, name)
  File "/usr/local/lib/python3.5/dist-packages/django/urls/conf.py", line 73, in _path
    raise TypeError('view must be a callable or a list/tuple in the case of include().')
TypeError: view must be a callable or a list/tuple in the case of include().
```

**Comment by azlev** [comment]
I came here because I get the same error.

I could solve the problems. Mostly are due out of date documentation.

diff --git a/betta/settings.py b/betta/settings.py
index 2b37aab..125fc28 100644
--- a/betta/settings.py
+++ b/betta/settings.py
@@ -31,6 +31,7 @@ ALLOWED_HOSTS = []
 # Application definition
 
 INSTALLED_APPS = [
+    'cas.apps.CASConfig',
     'django.contrib.admin',
     'django.contrib.auth',
@@ -43,6 +44,8 @@ INSTALLED_APPS = [
 MIDDLEWARE = [
     'django.middleware.security.SecurityMiddleware',
     'django.contrib.sessions.middleware.SessionMiddleware',
+    'django.contrib.auth.middleware.AuthenticationMiddleware',
+    'cas.middleware.CASMiddleware',
     'django.middleware.common.CommonMiddleware',
     'django.middleware.csrf.CsrfViewMiddleware',
     'django.contrib.auth.middleware.AuthenticationMiddleware',
@@ -50,6 +53,11 @@ MIDDLEWARE = [
     'django.middleware.clickjacking.XFrameOptionsMiddleware',
 ]
 
+AUTHENTICATION_BACKENDS = (
+'django.contrib.auth.backends.ModelBackend',
+'cas.backends.CASBackend',
+)
+
+
+CAS_SERVER_URL="http://bla"
